name: Lint, Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - uses: actions/setup-node@v2
      - name: Install node dependencies
        run: npm install

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run lint check
        run: npm run lint:check

      - name: Run tests
        run: make test